-- =====================================================
-- Reading PRO 진단 평가 관련 테이블 스키마
-- 학생 진단, 평가 결과, 피드백 등을 저장
-- =====================================================

-- 1) 진단 세션 (학생이 받는 진단 평가)
CREATE TABLE IF NOT EXISTS public.assessment_sessions (
  session_id bigint generated by default as identity primary key,
  student_id bigint NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
  assigned_by bigint REFERENCES public.users(user_id) ON DELETE SET NULL, -- 배정한 교사
  grade_band text NOT NULL CHECK (grade_band IN ('초저', '초고', '중저', '중고')),
  stimulus_id bigint REFERENCES public.stimuli(stimulus_id) ON DELETE SET NULL,
  
  -- 진단 상태
  status text NOT NULL DEFAULT 'assigned' CHECK (status IN (
    'assigned',      -- 배정됨
    'in_progress',   -- 진행 중
    'submitted',     -- 제출됨
    'ai_evaluated',  -- AI 평가 완료
    'teacher_reviewed', -- 교사 검토 완료
    'completed'      -- 최종 완료
  )),
  
  -- 시간 정보
  time_limit_minutes integer DEFAULT 60,
  started_at timestamptz,
  submitted_at timestamptz,
  
  -- 메타데이터
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_assessment_sessions_student ON public.assessment_sessions(student_id, status);
CREATE INDEX IF NOT EXISTS idx_assessment_sessions_teacher ON public.assessment_sessions(assigned_by);

-- 2) 학생 답안
CREATE TABLE IF NOT EXISTS public.student_answers (
  answer_id bigint generated by default as identity primary key,
  session_id bigint NOT NULL REFERENCES public.assessment_sessions(session_id) ON DELETE CASCADE,
  item_id bigint REFERENCES public.item_bank(item_id) ON DELETE SET NULL, -- 문항은행 문항
  
  -- 답안 내용
  answer_content text NOT NULL,
  word_count integer,
  char_count integer,
  
  -- 자동 저장
  auto_saved_at timestamptz,
  submitted_at timestamptz,
  
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_student_answers_session ON public.student_answers(session_id);

-- 3) AI 평가 결과
CREATE TABLE IF NOT EXISTS public.ai_evaluations (
  evaluation_id bigint generated by default as identity primary key,
  session_id bigint NOT NULL REFERENCES public.assessment_sessions(session_id) ON DELETE CASCADE,
  answer_id bigint REFERENCES public.student_answers(answer_id) ON DELETE SET NULL,
  
  -- 영역별 점수 (각 25점 만점, 총 100점)
  comprehension_score numeric(5,2) DEFAULT 0,      -- 이해력
  inference_score numeric(5,2) DEFAULT 0,          -- 추론력
  critical_score numeric(5,2) DEFAULT 0,           -- 비판적 사고
  expression_score numeric(5,2) DEFAULT 0,         -- 표현력
  total_score numeric(5,2) DEFAULT 0,
  
  -- 등급 및 백분위
  grade_level text,  -- A, B, C, D
  percentile integer,
  
  -- AI 분석 상세 (JSON)
  rubric_scores jsonb DEFAULT '[]'::jsonb,  -- 루브릭별 상세 점수
  strengths jsonb DEFAULT '[]'::jsonb,      -- 강점
  weaknesses jsonb DEFAULT '[]'::jsonb,     -- 약점
  
  -- AI 피드백 (JSON)
  student_feedback jsonb DEFAULT '{}'::jsonb,  -- 학생용 피드백
  detailed_feedback jsonb DEFAULT '{}'::jsonb, -- 상세 피드백
  line_edits jsonb DEFAULT '[]'::jsonb,        -- 문장별 첨삭
  
  -- 오류 분석
  spelling_errors integer DEFAULT 0,
  grammar_errors integer DEFAULT 0,
  
  evaluated_at timestamptz NOT NULL DEFAULT now(),
  model_used text  -- 사용된 AI 모델
);

CREATE INDEX IF NOT EXISTS idx_ai_evaluations_session ON public.ai_evaluations(session_id);

-- 4) 교사 피드백 (AI 평가에 대한 교사 검토/추가)
CREATE TABLE IF NOT EXISTS public.teacher_feedbacks (
  feedback_id bigint generated by default as identity primary key,
  evaluation_id bigint NOT NULL REFERENCES public.ai_evaluations(evaluation_id) ON DELETE CASCADE,
  teacher_id bigint NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
  
  -- 교사 수정 점수 (NULL이면 AI 점수 유지)
  adjusted_total_score numeric(5,2),
  adjusted_grade text,
  
  -- 교사 피드백
  summary_intro text,     -- 서론 피드백
  summary_body text,      -- 본론 피드백
  summary_conclusion text, -- 결론 피드백
  
  topic_understanding text,  -- 주제 이해도
  example_analysis text,     -- 사례 분석
  logical_flow text,         -- 논리적 전개
  expression_quality text,   -- 표현력
  
  overall_comment text,      -- 종합 코멘트
  
  feedback_status text DEFAULT 'draft' CHECK (feedback_status IN ('draft', 'completed')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_teacher_feedbacks_evaluation ON public.teacher_feedbacks(evaluation_id);
CREATE INDEX IF NOT EXISTS idx_teacher_feedbacks_teacher ON public.teacher_feedbacks(teacher_id);

-- 5) 학생-학부모 관계
CREATE TABLE IF NOT EXISTS public.student_parent_relations (
  relation_id bigint generated by default as identity primary key,
  student_id bigint NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
  parent_id bigint NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
  relationship text DEFAULT 'parent', -- parent, guardian
  is_primary boolean DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(student_id, parent_id)
);

CREATE INDEX IF NOT EXISTS idx_student_parent_student ON public.student_parent_relations(student_id);
CREATE INDEX IF NOT EXISTS idx_student_parent_parent ON public.student_parent_relations(parent_id);

-- 6) 학급 관리
CREATE TABLE IF NOT EXISTS public.classes (
  class_id bigint generated by default as identity primary key,
  school_id bigint,
  class_name text NOT NULL,
  grade integer NOT NULL,
  academic_year integer NOT NULL DEFAULT EXTRACT(YEAR FROM CURRENT_DATE),
  teacher_id bigint REFERENCES public.users(user_id) ON DELETE SET NULL,
  is_active boolean DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_classes_teacher ON public.classes(teacher_id);
CREATE INDEX IF NOT EXISTS idx_classes_school ON public.classes(school_id);

-- 7) 학급-학생 관계
CREATE TABLE IF NOT EXISTS public.class_students (
  id bigint generated by default as identity primary key,
  class_id bigint NOT NULL REFERENCES public.classes(class_id) ON DELETE CASCADE,
  student_id bigint NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
  enrolled_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(class_id, student_id)
);

-- RLS 설정
ALTER TABLE public.assessment_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_answers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_evaluations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teacher_feedbacks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_parent_relations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.classes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.class_students ENABLE ROW LEVEL SECURITY;

-- 개발용 전체 접근 정책
CREATE POLICY "Allow all for assessment_sessions" ON public.assessment_sessions FOR ALL USING (true);
CREATE POLICY "Allow all for student_answers" ON public.student_answers FOR ALL USING (true);
CREATE POLICY "Allow all for ai_evaluations" ON public.ai_evaluations FOR ALL USING (true);
CREATE POLICY "Allow all for teacher_feedbacks" ON public.teacher_feedbacks FOR ALL USING (true);
CREATE POLICY "Allow all for student_parent_relations" ON public.student_parent_relations FOR ALL USING (true);
CREATE POLICY "Allow all for classes" ON public.classes FOR ALL USING (true);
CREATE POLICY "Allow all for class_students" ON public.class_students FOR ALL USING (true);

-- 권한 부여
GRANT ALL ON public.assessment_sessions TO anon;
GRANT ALL ON public.student_answers TO anon;
GRANT ALL ON public.ai_evaluations TO anon;
GRANT ALL ON public.teacher_feedbacks TO anon;
GRANT ALL ON public.student_parent_relations TO anon;
GRANT ALL ON public.classes TO anon;
GRANT ALL ON public.class_students TO anon;
