-- =========================================================
-- 문항은행(Item Bank) + 지문(Stimulus) + 루브릭(Rubric) + 영역(Domain) + 문항 제작 워크스페이스(Authoring)
-- 리딩 PRO 문해력 진단 시스템용
-- =========================================================

-- =========================================================
-- 0) Extensions
-- =========================================================
create extension if not exists pgcrypto;

-- =========================================================
-- 1) Core taxonomy: domains (문해력 영역 + 독자성향)
-- =========================================================
create table if not exists public.domains (
  domain_id bigint generated by default as identity primary key,
  code text not null unique,                        -- e.g., "LIT_UNDERSTANDING", "DISP_A"
  name text not null,                               -- display name
  domain_type text not null check (domain_type in (
    'literacy_main',      -- 문해력 대분류 (이해력, 심미적감수성, 의사소통능력)
    'literacy_sub',       -- 문해력 소분류 (사실적이해, 추론적이해 등)
    'disposition_type',   -- 독자성향 유형 (A, B, C, D)
    'disposition_factor', -- 독자성향 요인
    'other'
  )),
  parent_domain_id bigint references public.domains(domain_id) on delete set null,
  description text,
  display_order integer default 0,
  created_at timestamptz not null default now()
);

create index if not exists idx_domains_parent on public.domains(parent_domain_id);
create index if not exists idx_domains_type on public.domains(domain_type);

-- =========================================================
-- 2) Stimuli (지문/자료)
-- =========================================================
create table if not exists public.stimuli (
  stimulus_id bigint generated by default as identity primary key,
  title text not null,
  content_type text not null check (content_type in ('text', 'html', 'markdown', 'image', 'table', 'pdf', 'mixed')),
  content_text text,                                -- extracted text or main body
  assets_json jsonb not null default '{}'::jsonb,    -- {files:[...], captions:[...]} etc.
  source_meta_json jsonb not null default '{}'::jsonb, -- {source, copyright, page, note}
  grade_band text not null check (grade_band in ('초저', '초고', '중저', '중고')),
  genre text,                                        -- 문학/비문학/복합 등
  word_count integer,
  created_by bigint references public.users(user_id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_stimuli_created_at on public.stimuli(created_at);
create index if not exists idx_stimuli_grade on public.stimuli(grade_band);

-- =========================================================
-- 3) Item bank (운영용 문항은행)
-- =========================================================
create table if not exists public.item_bank (
  item_id bigint generated by default as identity primary key,
  item_code text unique,                            -- optional human-friendly id
  grade_band text not null check (grade_band in ('초저', '초고', '중저', '중고')),
  item_type text not null check (
    item_type in (
      'mcq_single', 'mcq_multi',
      'short_text', 'essay',
      'fill_blank', 'composite',
      'survey'
    )
  ),
  stimulus_id bigint references public.stimuli(stimulus_id) on delete set null,
  stem text not null,                               -- question prompt
  max_score numeric(10,2) not null default 1,
  difficulty_level integer check (difficulty_level between 1 and 5),
  constraints_json jsonb not null default '{}'::jsonb, -- char_limit, required_format...
  is_active boolean not null default true,
  created_by bigint references public.users(user_id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_item_bank_grade_type on public.item_bank(grade_band, item_type);
create index if not exists idx_item_bank_stimulus on public.item_bank(stimulus_id);
create index if not exists idx_item_bank_active on public.item_bank(is_active) where is_active = true;

-- 문항-영역 매핑 (대분류/소분류, 가중치 포함)
create table if not exists public.item_domain_map (
  item_id bigint not null references public.item_bank(item_id) on delete cascade,
  domain_id bigint not null references public.domains(domain_id) on delete restrict,
  weight numeric(10,4) not null default 1,
  primary_flag boolean not null default false,
  created_at timestamptz not null default now(),
  primary key (item_id, domain_id)
);

create index if not exists idx_item_domain_domain on public.item_domain_map(domain_id);

-- =========================================================
-- 4) MCQ options + option scoring (근접점수/오답이유)
-- =========================================================
create table if not exists public.item_options (
  option_id bigint generated by default as identity primary key,
  item_id bigint not null references public.item_bank(item_id) on delete cascade,
  label text,                                       -- "①" or "A"
  option_text text not null,
  display_order integer not null default 1,
  created_at timestamptz not null default now()
);

create index if not exists idx_item_options_item on public.item_options(item_id);

create table if not exists public.item_option_scoring (
  option_id bigint primary key references public.item_options(option_id) on delete cascade,
  is_correct boolean not null default false,
  partial_score numeric(10,2) not null default 0,   -- 근접점수
  rationale_text text,                              -- 오답 이유 / 해설
  misconception_tag text,
  updated_at timestamptz not null default now()
);

-- =========================================================
-- 5) Composite parts (복합문항 파트)
-- =========================================================
create table if not exists public.item_parts (
  part_id bigint generated by default as identity primary key,
  item_id bigint not null references public.item_bank(item_id) on delete cascade,
  part_type text not null check (part_type in ('mcq', 'blank', 'short_text', 'essay')),
  part_prompt text not null,
  max_score numeric(10,2) not null default 1,
  constraints_json jsonb not null default '{}'::jsonb,
  display_order integer not null default 1,
  created_at timestamptz not null default now()
);

create index if not exists idx_item_parts_item on public.item_parts(item_id);

-- =========================================================
-- 6) Answer keys (객관식 정답/복수정답/텍스트 정답/규칙형)
-- =========================================================
create table if not exists public.item_keys (
  key_id bigint generated by default as identity primary key,
  target_type text not null check (target_type in ('item', 'part')),
  target_item_id bigint references public.item_bank(item_id) on delete cascade,
  target_part_id bigint references public.item_parts(part_id) on delete cascade,
  answer_type text not null check (
    answer_type in ('single_option', 'multi_option', 'text_exact', 'regex', 'keyword_set', 'rubric_only', 'manual_only')
  ),
  correct_option_ids bigint[] not null default '{}',
  correct_text text,
  scoring_rules_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint chk_item_keys_target
    check (
      (target_type = 'item' and target_item_id is not null and target_part_id is null) or
      (target_type = 'part' and target_part_id is not null and target_item_id is null)
    )
);

create index if not exists idx_item_keys_item on public.item_keys(target_item_id);
create index if not exists idx_item_keys_part on public.item_keys(target_part_id);

-- =========================================================
-- 7) Rubrics (서술형/규칙형/예시답안 포함)
-- =========================================================
create table if not exists public.rubrics (
  rubric_id bigint generated by default as identity primary key,
  rubric_type text not null check (rubric_type in ('level_descriptors', 'analytic', 'checklist_rules', 'exemplar_only', 'mixed')),
  target_type text not null check (target_type in ('item', 'part')),
  item_id bigint references public.item_bank(item_id) on delete cascade,
  part_id bigint references public.item_parts(part_id) on delete cascade,
  rubric_json jsonb not null default '{}'::jsonb,
  version integer not null default 1,
  created_by bigint references public.users(user_id) on delete set null,
  created_at timestamptz not null default now(),
  constraint chk_rubrics_target
    check (
      (target_type = 'item' and item_id is not null and part_id is null) or
      (target_type = 'part' and part_id is not null and item_id is null)
    )
);

create index if not exists idx_rubrics_item on public.rubrics(item_id);
create index if not exists idx_rubrics_part on public.rubrics(part_id);

-- 루브릭 구조화 테이블들
create table if not exists public.rubric_criteria (
  criterion_id bigint generated by default as identity primary key,
  rubric_id bigint not null references public.rubrics(rubric_id) on delete cascade,
  name text not null,
  weight numeric(10,4) not null default 1,
  max_points numeric(10,2),
  display_order integer not null default 1
);

create table if not exists public.rubric_levels (
  level_id bigint generated by default as identity primary key,
  criterion_id bigint not null references public.rubric_criteria(criterion_id) on delete cascade,
  level_value integer not null,
  descriptor text not null,
  points numeric(10,2) not null default 0
);

create table if not exists public.rubric_rules (
  rule_id bigint generated by default as identity primary key,
  rubric_id bigint not null references public.rubrics(rubric_id) on delete cascade,
  rule_type text not null,
  rule_json jsonb not null default '{}'::jsonb
);

create table if not exists public.rubric_exemplars (
  exemplar_id bigint generated by default as identity primary key,
  rubric_id bigint not null references public.rubrics(rubric_id) on delete cascade,
  exemplar_text text not null,
  score numeric(10,2),
  notes text
);

-- =========================================================
-- 8) Authoring workspace (AI 초안 → 다수 교사 검토 → publish)
-- =========================================================
create table if not exists public.authoring_projects (
  project_id bigint generated by default as identity primary key,
  title text not null,
  grade_band text not null check (grade_band in ('초저', '초고', '중저', '중고')),
  topic_tags text[] not null default '{}',
  difficulty_target integer check (difficulty_target between 1 and 5),
  status text not null default 'draft' check (status in ('draft','in_review','approved','published','archived')),
  settings_json jsonb not null default '{}'::jsonb,
  created_by bigint references public.users(user_id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_authoring_projects_status on public.authoring_projects(status);

create table if not exists public.authoring_assets (
  asset_id bigint generated by default as identity primary key,
  project_id bigint not null references public.authoring_projects(project_id) on delete cascade,
  asset_type text not null check (asset_type in ('passage','image','pdf','table','audio','other')),
  storage_url text not null,
  extracted_text text,
  meta_json jsonb not null default '{}'::jsonb,
  created_by bigint references public.users(user_id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.ai_generation_jobs (
  job_id bigint generated by default as identity primary key,
  project_id bigint not null references public.authoring_projects(project_id) on delete cascade,
  requested_by bigint references public.users(user_id) on delete set null,
  input_spec_json jsonb not null default '{}'::jsonb,
  model_name text,
  status text not null default 'queued' check (status in ('queued','running','succeeded','failed')),
  created_at timestamptz not null default now(),
  completed_at timestamptz,
  error_text text
);

create table if not exists public.ai_generation_outputs (
  output_id bigint generated by default as identity primary key,
  job_id bigint not null references public.ai_generation_jobs(job_id) on delete cascade,
  output_json jsonb not null,
  created_at timestamptz not null default now()
);

create table if not exists public.authoring_items (
  draft_item_id bigint generated by default as identity primary key,
  project_id bigint not null references public.authoring_projects(project_id) on delete cascade,
  item_kind text not null check (item_kind in ('mcq','essay','composite','survey')),
  status text not null default 'ai_draft' check (status in ('ai_draft','editing','in_review','approved','rejected')),
  current_version_id bigint,
  created_at timestamptz not null default now()
);

create table if not exists public.authoring_item_versions (
  version_id bigint generated by default as identity primary key,
  draft_item_id bigint not null references public.authoring_items(draft_item_id) on delete cascade,
  based_on_version_id bigint references public.authoring_item_versions(version_id) on delete set null,
  editor_user_id bigint references public.users(user_id) on delete set null,
  content_json jsonb not null,
  change_summary text,
  created_at timestamptz not null default now()
);

alter table public.authoring_items
  add constraint fk_authoring_items_current_version
  foreign key (current_version_id) references public.authoring_item_versions(version_id) on delete set null;

create index if not exists idx_authoring_items_project on public.authoring_items(project_id, status);

create table if not exists public.authoring_rubrics (
  draft_rubric_id bigint generated by default as identity primary key,
  project_id bigint not null references public.authoring_projects(project_id) on delete cascade,
  linked_draft_item_id bigint references public.authoring_items(draft_item_id) on delete set null,
  status text not null default 'ai_draft' check (status in ('ai_draft','editing','in_review','approved')),
  current_version_id bigint,
  created_at timestamptz not null default now()
);

create table if not exists public.authoring_rubric_versions (
  version_id bigint generated by default as identity primary key,
  draft_rubric_id bigint not null references public.authoring_rubrics(draft_rubric_id) on delete cascade,
  editor_user_id bigint references public.users(user_id) on delete set null,
  rubric_json jsonb not null,
  change_summary text,
  created_at timestamptz not null default now()
);

alter table public.authoring_rubrics
  add constraint fk_authoring_rubrics_current_version
  foreign key (current_version_id) references public.authoring_rubric_versions(version_id) on delete set null;

create table if not exists public.authoring_item_reviews (
  review_id bigint generated by default as identity primary key,
  draft_item_id bigint not null references public.authoring_items(draft_item_id) on delete cascade,
  round_no integer not null default 1,
  status text not null default 'open' check (status in ('open','closed')),
  created_by bigint references public.users(user_id) on delete set null,
  created_at timestamptz not null default now(),
  closed_at timestamptz
);

create table if not exists public.authoring_review_assignments (
  review_id bigint not null references public.authoring_item_reviews(review_id) on delete cascade,
  reviewer_user_id bigint not null references public.users(user_id) on delete cascade,
  role text not null default 'secondary' check (role in ('primary','secondary','moderator')),
  decision text check (decision in ('approve','request_changes','reject','abstain')),
  decision_comment text,
  decided_at timestamptz,
  primary key (review_id, reviewer_user_id)
);

create table if not exists public.authoring_comments (
  comment_id bigint generated by default as identity primary key,
  draft_item_id bigint not null references public.authoring_items(draft_item_id) on delete cascade,
  version_id bigint references public.authoring_item_versions(version_id) on delete set null,
  author_user_id bigint references public.users(user_id) on delete set null,
  anchor_json jsonb not null default '{}'::jsonb,
  comment_text text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.authoring_change_requests (
  cr_id bigint generated by default as identity primary key,
  draft_item_id bigint not null references public.authoring_items(draft_item_id) on delete cascade,
  created_by bigint references public.users(user_id) on delete set null,
  severity text not null default 'should' check (severity in ('must','should','could')),
  request_text text not null,
  status text not null default 'open' check (status in ('open','resolved','wontfix')),
  resolved_by bigint references public.users(user_id) on delete set null,
  resolved_at timestamptz,
  created_at timestamptz not null default now()
);

-- Publish event mapping
create table if not exists public.publish_events (
  publish_id bigint generated by default as identity primary key,
  project_id bigint not null references public.authoring_projects(project_id) on delete cascade,
  published_by bigint references public.users(user_id) on delete set null,
  published_at timestamptz not null default now(),
  notes text
);

create table if not exists public.published_item_map (
  publish_id bigint not null references public.publish_events(publish_id) on delete cascade,
  draft_item_id bigint not null references public.authoring_items(draft_item_id) on delete restrict,
  final_item_id bigint references public.item_bank(item_id) on delete set null,
  final_rubric_id bigint references public.rubrics(rubric_id) on delete set null,
  final_stimulus_id bigint references public.stimuli(stimulus_id) on delete set null,
  primary key (publish_id, draft_item_id)
);

-- =========================================================
-- 9) Updated_at trigger
-- =========================================================
create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

do $$
begin
  if not exists (select 1 from pg_trigger where tgname = 'trg_stimuli_updated_at') then
    create trigger trg_stimuli_updated_at
    before update on public.stimuli
    for each row execute function public.set_updated_at();
  end if;

  if not exists (select 1 from pg_trigger where tgname = 'trg_item_bank_updated_at') then
    create trigger trg_item_bank_updated_at
    before update on public.item_bank
    for each row execute function public.set_updated_at();
  end if;

  if not exists (select 1 from pg_trigger where tgname = 'trg_authoring_projects_updated_at') then
    create trigger trg_authoring_projects_updated_at
    before update on public.authoring_projects
    for each row execute function public.set_updated_at();
  end if;
end $$;

-- =========================================================
-- 10) RLS Policies (문항 개발 교사 전용 권한)
-- =========================================================

-- RLS 활성화
alter table public.domains enable row level security;
alter table public.stimuli enable row level security;
alter table public.item_bank enable row level security;
alter table public.item_domain_map enable row level security;
alter table public.item_options enable row level security;
alter table public.item_option_scoring enable row level security;
alter table public.item_parts enable row level security;
alter table public.item_keys enable row level security;
alter table public.rubrics enable row level security;
alter table public.rubric_criteria enable row level security;
alter table public.rubric_levels enable row level security;
alter table public.rubric_rules enable row level security;
alter table public.rubric_exemplars enable row level security;
alter table public.authoring_projects enable row level security;
alter table public.authoring_assets enable row level security;
alter table public.ai_generation_jobs enable row level security;
alter table public.ai_generation_outputs enable row level security;
alter table public.authoring_items enable row level security;
alter table public.authoring_item_versions enable row level security;
alter table public.authoring_rubrics enable row level security;
alter table public.authoring_rubric_versions enable row level security;
alter table public.authoring_item_reviews enable row level security;
alter table public.authoring_review_assignments enable row level security;
alter table public.authoring_comments enable row level security;
alter table public.authoring_change_requests enable row level security;
alter table public.publish_events enable row level security;
alter table public.published_item_map enable row level security;

-- anon 역할에 기본 권한 부여 (개발/테스트용)
grant usage on schema public to anon;
grant select on public.domains to anon;
grant select, insert, update, delete on public.stimuli to anon;
grant select, insert, update, delete on public.item_bank to anon;
grant select, insert, update, delete on public.item_domain_map to anon;
grant select, insert, update, delete on public.item_options to anon;
grant select, insert, update, delete on public.item_option_scoring to anon;
grant select, insert, update, delete on public.item_parts to anon;
grant select, insert, update, delete on public.item_keys to anon;
grant select, insert, update, delete on public.rubrics to anon;
grant select, insert, update, delete on public.rubric_criteria to anon;
grant select, insert, update, delete on public.rubric_levels to anon;
grant select, insert, update, delete on public.rubric_rules to anon;
grant select, insert, update, delete on public.rubric_exemplars to anon;
grant select, insert, update, delete on public.authoring_projects to anon;
grant select, insert, update, delete on public.authoring_assets to anon;
grant select, insert, update, delete on public.ai_generation_jobs to anon;
grant select, insert, update, delete on public.ai_generation_outputs to anon;
grant select, insert, update, delete on public.authoring_items to anon;
grant select, insert, update, delete on public.authoring_item_versions to anon;
grant select, insert, update, delete on public.authoring_rubrics to anon;
grant select, insert, update, delete on public.authoring_rubric_versions to anon;
grant select, insert, update, delete on public.authoring_item_reviews to anon;
grant select, insert, update, delete on public.authoring_review_assignments to anon;
grant select, insert, update, delete on public.authoring_comments to anon;
grant select, insert, update, delete on public.authoring_change_requests to anon;
grant select, insert, update, delete on public.publish_events to anon;
grant select, insert, update, delete on public.published_item_map to anon;

-- RLS 정책: 모든 사용자 조회 허용 (개발용)
create policy "Allow all for domains" on public.domains for all using (true);
create policy "Allow all for stimuli" on public.stimuli for all using (true);
create policy "Allow all for item_bank" on public.item_bank for all using (true);
create policy "Allow all for item_domain_map" on public.item_domain_map for all using (true);
create policy "Allow all for item_options" on public.item_options for all using (true);
create policy "Allow all for item_option_scoring" on public.item_option_scoring for all using (true);
create policy "Allow all for item_parts" on public.item_parts for all using (true);
create policy "Allow all for item_keys" on public.item_keys for all using (true);
create policy "Allow all for rubrics" on public.rubrics for all using (true);
create policy "Allow all for rubric_criteria" on public.rubric_criteria for all using (true);
create policy "Allow all for rubric_levels" on public.rubric_levels for all using (true);
create policy "Allow all for rubric_rules" on public.rubric_rules for all using (true);
create policy "Allow all for rubric_exemplars" on public.rubric_exemplars for all using (true);
create policy "Allow all for authoring_projects" on public.authoring_projects for all using (true);
create policy "Allow all for authoring_assets" on public.authoring_assets for all using (true);
create policy "Allow all for ai_generation_jobs" on public.ai_generation_jobs for all using (true);
create policy "Allow all for ai_generation_outputs" on public.ai_generation_outputs for all using (true);
create policy "Allow all for authoring_items" on public.authoring_items for all using (true);
create policy "Allow all for authoring_item_versions" on public.authoring_item_versions for all using (true);
create policy "Allow all for authoring_rubrics" on public.authoring_rubrics for all using (true);
create policy "Allow all for authoring_rubric_versions" on public.authoring_rubric_versions for all using (true);
create policy "Allow all for authoring_item_reviews" on public.authoring_item_reviews for all using (true);
create policy "Allow all for authoring_review_assignments" on public.authoring_review_assignments for all using (true);
create policy "Allow all for authoring_comments" on public.authoring_comments for all using (true);
create policy "Allow all for authoring_change_requests" on public.authoring_change_requests for all using (true);
create policy "Allow all for publish_events" on public.publish_events for all using (true);
create policy "Allow all for published_item_map" on public.published_item_map for all using (true);

-- =========================================================
-- 11) 초기 데이터: 문해력 영역 및 독자성향 유형
-- =========================================================
insert into public.domains (code, name, domain_type, description, display_order) values
-- 문해력 대분류
('LIT_UNDERSTANDING', '이해력', 'literacy_main', '글의 내용을 정확히 파악하고 추론하는 능력', 1),
('LIT_AESTHETIC', '심미적 감수성', 'literacy_main', '문학 작품을 감상하며 아름다움이나 의미를 느끼고 공감하는 능력', 2),
('LIT_COMMUNICATION', '의사소통 능력', 'literacy_main', '글을 통해 생각을 표현하고 다른 사람과 상호 작용하는 능력', 3)
on conflict (code) do nothing;

-- 이해력 소분류
insert into public.domains (code, name, domain_type, parent_domain_id, description, display_order)
select 'LIT_FACTUAL', '사실적 이해', 'literacy_sub', domain_id, '글에 명시된 정보를 이해', 1
from public.domains where code = 'LIT_UNDERSTANDING'
on conflict (code) do nothing;

insert into public.domains (code, name, domain_type, parent_domain_id, description, display_order)
select 'LIT_INFERENTIAL', '추론적 이해', 'literacy_sub', domain_id, '글에 나타나지 않은 내용을 추론', 2
from public.domains where code = 'LIT_UNDERSTANDING'
on conflict (code) do nothing;

insert into public.domains (code, name, domain_type, parent_domain_id, description, display_order)
select 'LIT_CRITICAL', '비판적 이해', 'literacy_sub', domain_id, '글의 내용과 논리를 평가', 3
from public.domains where code = 'LIT_UNDERSTANDING'
on conflict (code) do nothing;

-- 심미적 감수성 소분류
insert into public.domains (code, name, domain_type, parent_domain_id, description, display_order)
select 'AES_EXPRESSION', '문학적 표현', 'literacy_sub', domain_id, '작가의 표현 기법과 언어의 아름다움에 대한 이해', 1
from public.domains where code = 'LIT_AESTHETIC'
on conflict (code) do nothing;

insert into public.domains (code, name, domain_type, parent_domain_id, description, display_order)
select 'AES_EMPATHY', '정서적 공감', 'literacy_sub', domain_id, '등장인물의 감정이나 상황에 공감하는 능력', 2
from public.domains where code = 'LIT_AESTHETIC'
on conflict (code) do nothing;

insert into public.domains (code, name, domain_type, parent_domain_id, description, display_order)
select 'AES_VALUE', '문학적 가치', 'literacy_sub', domain_id, '작품이 담고 있는 주제·의식이나 교훈을 파악하는 능력', 3
from public.domains where code = 'LIT_AESTHETIC'
on conflict (code) do nothing;

-- 의사소통 능력 소분류
insert into public.domains (code, name, domain_type, parent_domain_id, description, display_order)
select 'COM_CREATIVE', '창의적 문제 해결', 'literacy_sub', domain_id, '텍스트 내용을 응용하여 새로운 해결책을 찾는 능력', 1
from public.domains where code = 'LIT_COMMUNICATION'
on conflict (code) do nothing;

insert into public.domains (code, name, domain_type, parent_domain_id, description, display_order)
select 'COM_EXPRESSION', '표현과 전달 능력', 'literacy_sub', domain_id, '이해 내용을 정확히 표현하고 전달하는 능력', 2
from public.domains where code = 'LIT_COMMUNICATION'
on conflict (code) do nothing;

insert into public.domains (code, name, domain_type, parent_domain_id, description, display_order)
select 'COM_SOCIAL', '사회적 상호작용', 'literacy_sub', domain_id, '읽은 내용을 바탕으로 타인과 소통하고 협력하는 능력', 3
from public.domains where code = 'LIT_COMMUNICATION'
on conflict (code) do nothing;

-- 독자성향 유형
insert into public.domains (code, name, domain_type, description, display_order) values
('DISP_A', 'A유형 (감성관계 중심)', 'disposition_type', '정서적 반응 요인과 사회적 동기 요인이 우세', 1),
('DISP_B', 'B유형 (인지·분석 중심)', 'disposition_type', '정보 처리 요인과 인지적 독서 동기가 우세', 2),
('DISP_C', 'C유형 (행동·습관 중심)', 'disposition_type', '독서 실천 행동과 자기조절 요인이 우세', 3),
('DISP_D', 'D유형 (자율·탐색 중심)', 'disposition_type', '호기심 기반 동기와 탐색적 독서 요인이 우세', 4)
on conflict (code) do nothing;
