-- =========================================================
-- 프롬프트 관리 시스템 (AI 문항 생성용)
-- 리딩 PRO 문해력 진단 시스템
-- 참조: docs/Prompt.md
-- =========================================================

-- =========================================================
-- 1) 기본 프롬프트 템플릿 (Base Prompt)
-- =========================================================
create table if not exists public.prompt_base_templates (
  base_template_id bigint generated by default as identity primary key,
  template_name text not null,                        -- 예: "중등 문해력 진단 v1"
  template_code text not null unique,                 -- 예: "MIDLEV_LITERACY_V1"
  persona_text text not null,                         -- [ROLE / PERSONA] 섹션
  input_schema_text text not null,                    -- [INPUT] 섹션 (플레이스홀더 포함)
  task_text text not null,                            -- [TASK] 섹션
  quality_rules_text text not null,                   -- [QUALITY RULES] 섹션
  output_format_text text not null,                   -- [OUTPUT FORMAT] JSON 스키마
  self_check_text text not null,                      -- [SELF-CHECK] 섹션
  placeholders jsonb not null default '[]'::jsonb,    -- 지원 플레이스홀더 목록
  target_grade_bands text[] default '{}',             -- 적용 학년군 (초저/초고/중저/중고)
  version integer not null default 1,
  is_active boolean not null default true,
  created_by bigint references public.users(user_id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_prompt_base_active on public.prompt_base_templates(is_active) where is_active = true;
create index if not exists idx_prompt_base_code on public.prompt_base_templates(template_code);

-- =========================================================
-- 2) 영역별 프롬프트 템플릿 (Area Prompt)
-- =========================================================
create table if not exists public.prompt_area_templates (
  area_template_id bigint generated by default as identity primary key,
  area_code text not null unique,                     -- 예: "READING_COMPREHENSION"
  area_name text not null,                            -- 예: "독해력 문항"
  area_description text,                              -- 영역 설명
  objective_text text not null,                       -- 목표 설명
  guidelines_text text not null,                      -- 문항 설계 지침
  example_patterns text,                              -- 문항 예시 유형
  skill_tags text[] not null default '{}',            -- 허용 skill tag 목록
  display_order integer not null default 1,
  is_active boolean not null default true,
  created_by bigint references public.users(user_id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_prompt_area_active on public.prompt_area_templates(is_active) where is_active = true;
create index if not exists idx_prompt_area_code on public.prompt_area_templates(area_code);

-- =========================================================
-- 3) Base-Area 호환성 매핑
-- =========================================================
create table if not exists public.prompt_base_area_map (
  base_template_id bigint not null references public.prompt_base_templates(base_template_id) on delete cascade,
  area_template_id bigint not null references public.prompt_area_templates(area_template_id) on delete cascade,
  is_default boolean not null default false,          -- 기본 선택 여부
  created_at timestamptz not null default now(),
  primary key (base_template_id, area_template_id)
);

-- =========================================================
-- 4) 사용자별 즐겨찾기/커스텀 프롬프트
-- =========================================================
create table if not exists public.prompt_user_favorites (
  favorite_id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(user_id) on delete cascade,
  favorite_name text not null,                        -- 사용자 지정 이름
  base_template_id bigint references public.prompt_base_templates(base_template_id) on delete set null,
  area_template_id bigint references public.prompt_area_templates(area_template_id) on delete set null,
  custom_prompt_text text,                            -- 사용자 커스텀 전체 프롬프트 (선택)
  custom_overrides jsonb not null default '{}'::jsonb, -- 특정 섹션만 오버라이드
  usage_count integer not null default 0,
  last_used_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists idx_prompt_favorites_user on public.prompt_user_favorites(user_id);

-- =========================================================
-- 5) 프롬프트 사용 로그 (효과 분석용)
-- =========================================================
create table if not exists public.prompt_usage_logs (
  log_id bigint generated by default as identity primary key,
  base_template_id bigint references public.prompt_base_templates(base_template_id) on delete set null,
  area_template_id bigint references public.prompt_area_templates(area_template_id) on delete set null,
  user_id bigint references public.users(user_id) on delete set null,
  project_id bigint references public.authoring_projects(project_id) on delete set null,
  stimulus_id bigint references public.stimuli(stimulus_id) on delete set null,
  final_prompt_text text,                             -- 실제 조합된 최종 프롬프트
  input_params jsonb not null default '{}'::jsonb,    -- 입력 파라미터 (난이도, 문항수 등)
  model_name text,                                    -- 사용된 AI 모델
  items_generated integer,                            -- 생성된 문항 수
  items_approved integer,                             -- 승인된 문항 수
  generation_time_ms integer,                         -- 생성 소요 시간
  quality_score numeric(5,2),                         -- 품질 점수 (검토 후 기록)
  created_at timestamptz not null default now()
);

create index if not exists idx_prompt_usage_base on public.prompt_usage_logs(base_template_id);
create index if not exists idx_prompt_usage_area on public.prompt_usage_logs(area_template_id);
create index if not exists idx_prompt_usage_created on public.prompt_usage_logs(created_at);
create index if not exists idx_prompt_usage_user on public.prompt_usage_logs(user_id);

-- =========================================================
-- 6) 프롬프트 버전 히스토리
-- =========================================================
create table if not exists public.prompt_version_history (
  history_id bigint generated by default as identity primary key,
  template_type text not null check (template_type in ('base', 'area')),
  template_id bigint not null,                        -- base_template_id 또는 area_template_id
  version integer not null,
  snapshot_json jsonb not null,                       -- 해당 버전의 전체 데이터 스냅샷
  change_summary text,                                -- 변경 사항 요약
  changed_by bigint references public.users(user_id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists idx_prompt_history_template on public.prompt_version_history(template_type, template_id);

-- =========================================================
-- 7) Updated_at 트리거
-- =========================================================
do $$
begin
  if not exists (select 1 from pg_trigger where tgname = 'trg_prompt_base_updated_at') then
    create trigger trg_prompt_base_updated_at
    before update on public.prompt_base_templates
    for each row execute function public.set_updated_at();
  end if;

  if not exists (select 1 from pg_trigger where tgname = 'trg_prompt_area_updated_at') then
    create trigger trg_prompt_area_updated_at
    before update on public.prompt_area_templates
    for each row execute function public.set_updated_at();
  end if;
end $$;

-- =========================================================
-- 8) RLS 정책 (개발용 - 모든 접근 허용)
-- =========================================================
alter table public.prompt_base_templates enable row level security;
alter table public.prompt_area_templates enable row level security;
alter table public.prompt_base_area_map enable row level security;
alter table public.prompt_user_favorites enable row level security;
alter table public.prompt_usage_logs enable row level security;
alter table public.prompt_version_history enable row level security;

create policy "Allow all for prompt_base_templates" on public.prompt_base_templates for all using (true);
create policy "Allow all for prompt_area_templates" on public.prompt_area_templates for all using (true);
create policy "Allow all for prompt_base_area_map" on public.prompt_base_area_map for all using (true);
create policy "Allow all for prompt_user_favorites" on public.prompt_user_favorites for all using (true);
create policy "Allow all for prompt_usage_logs" on public.prompt_usage_logs for all using (true);
create policy "Allow all for prompt_version_history" on public.prompt_version_history for all using (true);

grant usage on schema public to anon;
grant select, insert, update, delete on public.prompt_base_templates to anon;
grant select, insert, update, delete on public.prompt_area_templates to anon;
grant select, insert, update, delete on public.prompt_base_area_map to anon;
grant select, insert, update, delete on public.prompt_user_favorites to anon;
grant select, insert, update, delete on public.prompt_usage_logs to anon;
grant select, insert, update, delete on public.prompt_version_history to anon;

-- =========================================================
-- 9) 초기 데이터: Base Prompt (Prompt.md 기반)
-- =========================================================
INSERT INTO public.prompt_base_templates (
  template_name, 
  template_code, 
  persona_text, 
  input_schema_text, 
  task_text,
  quality_rules_text, 
  output_format_text, 
  self_check_text, 
  placeholders, 
  target_grade_bands
) VALUES (
  '중등 문해력 진단 평가 v1',
  'MIDLEV_LITERACY_V1',
  E'너는 ''중등 문해력 진단 평가''의 수석 문항 개발자이자 평가전문가다.\n너의 목표는 주어진 지문(자료)을 바탕으로 특정 영역(독해/추론/어휘/비판/요약)을 유의미하게 측정하는 문항을 설계하는 것이다.\n문항은 학교 현장에서 채점·해설이 가능해야 하며, 정답의 근거가 지문에 명확히 존재해야 한다.',
  E'- stimulus_id: {STIMULUS_ID}\n- grade_band: {GRADE_BAND}          # 예: 초저/초고/중저/중고\n- difficulty_level: {DIFFICULTY}    # 1~5\n- num_items: {NUM_ITEMS}            # 생성 문항 수\n- num_options: {NUM_OPTIONS}        # 객관식 보기 개수(예: 3/4/5)\n- stimulus_text:\n<<<STIMULUS_TEXT_BEGIN>>>\n{STIMULUS_TEXT}\n<<<STIMULUS_TEXT_END>>>',
  E'1) 아래 ''영역 맞춤 지시문(AREA_PROMPT)''을 기준으로 객관식 문항을 num_items개 생성하라.\n2) 각 문항은 (a) 지문 근거가 명확한 정답 1개, (b) 그럴듯하지만 명확히 오답인 오답 보기들로 구성하라.\n3) 각 문항마다 정답 근거(지문 내 단서/문장 요약)를 간단히 제시하고, 오답이 왜 오답인지도 간단히 설명하라.\n4) 문항 간 중복(같은 정답 근거/같은 사고 과정/같은 표현)을 피하고, 난이도를 difficulty_level에 맞춰 조절하라.',
  E'- 정답은 ''하나''만 존재해야 한다(복수정답 금지).\n- 보기들은 길이·문체·정보량이 비슷해야 한다(정답만 유독 길거나 단정적이면 안 됨).\n- "모두/항상/절대" 같은 과도하게 단정적인 표현을 오답 신호로 남발하지 말 것.\n- 지문에 없는 사실을 정답 근거로 쓰지 말 것(추론 문항이라도 ''지문 단서 기반''이어야 함).\n- 저작권 보호: 지문을 문항/보기/해설에 길게 그대로 복사하지 말고, 필요한 경우 ''의미를 바꿔 표현(패러프레이즈)''하라.\n- 학년군에 맞는 어휘·문장 길이를 유지하라.',
  E'{\n  "stimulus_id": "string",\n  "grade_band": "string",\n  "difficulty_level": number,\n  "area_code": "string",\n  "items": [\n    {\n      "item_no": number,\n      "stem": "string",\n      "options": ["string", "..."],\n      "correct_index": number,\n      "answer_rationale": "string",\n      "distractor_rationales": ["string", "..."],\n      "evidence": "string",\n      "tags": {\n        "area": "string",\n        "skill": "string",\n        "difficulty": number\n      }\n    }\n  ]\n}',
  E'출력 직전에 다음을 점검하고, 위배되면 스스로 수정한 뒤 출력하라.\n- (1) 각 문항에 정답이 1개뿐인가?\n- (2) 정답 근거가 지문에 있는가? (추론은 ''단서 기반''인가?)\n- (3) 보기들이 정답 신호를 과도하게 드러내지 않는가?\n- (4) 문항들이 서로 중복되지 않는가?\n- (5) num_options와 num_items를 정확히 지켰는가?',
  '["STIMULUS_ID", "GRADE_BAND", "DIFFICULTY", "NUM_ITEMS", "NUM_OPTIONS", "STIMULUS_TEXT", "AREA_PROMPT"]'::jsonb,
  ARRAY['초저', '초고', '중저', '중고']
) ON CONFLICT (template_code) DO NOTHING;

-- =========================================================
-- 10) 초기 데이터: Area Prompts (5개 영역)
-- =========================================================

-- 2-1) 독해력 문항
INSERT INTO public.prompt_area_templates (
  area_code, area_name, area_description, objective_text, guidelines_text, example_patterns, skill_tags, display_order
) VALUES (
  'READING_COMPREHENSION', 
  '독해력 문항', 
  '텍스트 명시 정보 기반',
  E'지문에 ''명시적으로 제시된 정보''를 정확히 찾고, 문장/단락 수준에서 의미를 확인하는 능력을 측정한다.',
  E'- 정답은 지문에 직접 근거가 있어야 하며, "찾아 읽기/정확한 이해"가 핵심이 되게 하라.\n- 단순 단어 찾기 수준을 넘어서, 다음 중 최소 1가지를 포함하라:\n  (a) 인물/사건/개념 관계, (b) 원인-결과, (c) 순서/절차, (d) 핵심 문장 식별, (e) 지시어/대상 확인\n- 오답 유형은 다음 중 2가지 이상 섞어라:\n  (1) 지문과 반대, (2) 일부만 맞고 핵심이 틀림, (3) 지문에 없는 내용, (4) 다른 단락 정보와 혼동',
  E'"지문에서 말하는 A의 특징으로 가장 적절한 것은?"\n"다음 중 지문 내용과 일치하는 것은?"',
  ARRAY['detail', 'relationship', 'sequence', 'reference'],
  1
) ON CONFLICT (area_code) DO NOTHING;

-- 2-2) 추론 문항
INSERT INTO public.prompt_area_templates (
  area_code, area_name, area_description, objective_text, guidelines_text, example_patterns, skill_tags, display_order
) VALUES (
  'INFERENCE', 
  '추론 문항', 
  '지문 단서 기반, 빈칸 추론/의도/함의',
  E'지문에 ''직접 쓰이지 않은 결론''을 지문 단서로부터 논리적으로 도출하는 능력을 측정한다.',
  E'- 정답은 반드시 ''지문 단서 2개 이상''으로 정당화 가능해야 한다.\n- "상식만으로 맞히는 문제"를 금지한다. 지문 단서가 핵심이어야 한다.\n- 다음 중 최소 1개를 포함하라:\n  (a) 글쓴이 의도/태도 추론, (b) 숨은 전제/함의, (c) 결과 예측, (d) 원인 추론, (e) 사례 일반화\n- 오답은 ''단서 1개만 보고 성급히 결론'' 또는 ''지문과 무관한 상식''으로 설계해라(그럴듯하지만 단서 부족).\n\nevidence에는 "단서1 + 단서2"를 한 줄로 요약해서 제시하라.',
  NULL,
  ARRAY['author_intent', 'implication', 'prediction', 'cause'],
  2
) ON CONFLICT (area_code) DO NOTHING;

-- 2-3) 어휘력 문항
INSERT INTO public.prompt_area_templates (
  area_code, area_name, area_description, objective_text, guidelines_text, example_patterns, skill_tags, display_order
) VALUES (
  'VOCAB_IN_CONTEXT', 
  '어휘력 문항', 
  '문맥 의미/용례/대체 표현',
  E'문맥 속 단어/표현의 의미를 파악하고, 적절한 대체 표현을 선택하는 능력을 측정한다.',
  E'- 지문에서 ''핵심 이해에 영향이 큰'' 단어/표현 1개를 선택하라(너무 쉬운 일상어 금지).\n- 가능한 유형:\n  (a) 문맥 의미 추론(가장 가까운 의미), (b) 대체 가능 표현, (c) 관용적/비유적 표현 해석\n- 보기 설계:\n  - 오답은 의미가 유사해 보이지만 문맥에 맞지 않게(뉘앙스/용례/정서) 설계하라.\n  - 정답과 오답은 모두 "그럴듯한 후보"로 만들되, 지문 문맥으로만 판별 가능해야 한다.\n- answer_rationale에는 "해당 표현이 쓰인 문맥 요약 + 왜 그 의미인지"를 포함하라.',
  NULL,
  ARRAY['context_meaning', 'nuance', 'substitution', 'figurative'],
  3
) ON CONFLICT (area_code) DO NOTHING;

-- 2-4) 비판적 사고 문항
INSERT INTO public.prompt_area_templates (
  area_code, area_name, area_description, objective_text, guidelines_text, example_patterns, skill_tags, display_order
) VALUES (
  'CRITICAL_THINKING', 
  '비판적 사고 문항', 
  '근거-주장, 논리 결함, 관점 평가',
  E'글의 주장과 근거를 구분하고, 논리적 타당성/신뢰성/편향 가능성을 점검하는 능력을 측정한다.',
  E'- 지문이 설명문/논설문/주장 포함 텍스트라면:\n  - 주장(claim), 근거(evidence), 예시(example), 결론(conclusion)을 구분하는 문항을 1개 이상 포함하라.\n- 지문이 이야기/서사라면:\n  - 인물의 판단/행동의 타당성, 관점의 편향, 대안의 합리성 평가 형태로 구성하라.\n- 다음 중 최소 1개 포함:\n  (a) 근거 부족/일반화/원인-결과 혼동 등 논리 약점 찾기\n  (b) 추가로 필요한 정보(검증 질문) 고르기\n  (c) 가장 타당한 반론/대안 선택\n- 오답은 "그럴듯한 비판처럼 보이지만 지문과 무관/과잉해석/근거 없는 단정"으로 설계하라.',
  NULL,
  ARRAY['claim_evidence', 'fallacy', 'check_needed', 'counterargument'],
  4
) ON CONFLICT (area_code) DO NOTHING;

-- 2-5) 요약 문항
INSERT INTO public.prompt_area_templates (
  area_code, area_name, area_description, objective_text, guidelines_text, example_patterns, skill_tags, display_order
) VALUES (
  'SUMMARIZATION', 
  '요약 문항', 
  '핵심/주제/제목, 불필요 정보 배제',
  E'지문의 핵심 내용을 추출하고, 부차적 정보를 배제하여 ''주제/요지''를 파악하는 능력을 측정한다.',
  E'- 유형 중 최소 1개:\n  (a) 가장 적절한 요약문 고르기\n  (b) 가장 적절한 제목/주제문 고르기\n  (c) 중심 내용에서 벗어난 문장 찾기(요약 관점)\n- 정답은 ''핵심 주장/핵심 사건/핵심 설명 구조''를 포함해야 하며,\n  오답은 다음 중 하나 이상에 해당하도록 설계하라:\n  (1) 세부사항만 나열, (2) 지엽적 예시만 강조, (3) 핵심 누락, (4) 과도한 일반화, (5) 지문과 반대\n- evidence에는 "핵심 키워드/핵심 관계"를 1줄로 요약해 제시하라.',
  NULL,
  ARRAY['main_idea', 'title', 'best_summary', 'off_topic'],
  5
) ON CONFLICT (area_code) DO NOTHING;

-- =========================================================
-- 11) Base-Area 매핑 초기 데이터
-- =========================================================
INSERT INTO public.prompt_base_area_map (base_template_id, area_template_id, is_default)
SELECT 
  b.base_template_id,
  a.area_template_id,
  (a.area_code = 'READING_COMPREHENSION')  -- 독해력을 기본값으로
FROM public.prompt_base_templates b
CROSS JOIN public.prompt_area_templates a
WHERE b.template_code = 'MIDLEV_LITERACY_V1'
ON CONFLICT DO NOTHING;
