-- 사용자 테이블만 포함한 간단한 스키마
-- user_type: STUDENT, PARENT, SCHOOL_ADMIN, ASSESSMENT_TEACHER, QUESTION_DEVELOPER, SYSTEM_ADMIN
-- student_grade_level: GRADE_A, GRADE_B (2단계)

create table if not exists public.users (
  user_id bigint generated by default as identity primary key,
  email text not null unique,
  name text not null,
  user_type text not null,
  birth_date date,
  phone text,
  school_name text,
  school_id bigint,
  grade integer,
  class_name text,
  student_grade_level text,
  profile_image_url text,
  is_active boolean default true,
  password_hash text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- RLS 설정
alter table public.users enable row level security;

-- 기존 정책 삭제
drop policy if exists "dev_read_users" on public.users;
drop policy if exists "dev_write_users" on public.users;
drop policy if exists "dev_update_users" on public.users;
drop policy if exists "dev_delete_users" on public.users;

-- 개발용 전체 접근 정책 (운영 전 수정 필요)
create policy "dev_read_users" on public.users for select using (true);
create policy "dev_write_users" on public.users for insert with check (true);
create policy "dev_update_users" on public.users for update using (true);
create policy "dev_delete_users" on public.users for delete using (true);

-- anon 역할 권한 (개발용)
grant usage on schema public to anon;
grant select on public.users to anon;
