-- Core tables for the literacy assessment app

create table if not exists public.users (
  user_id bigint generated by default as identity primary key,
  email text not null unique,
  name text not null,
  user_type text not null,
  birth_date date,
  phone text,
  school_name text,
  grade integer,
  profile_image_url text,
  is_active boolean default true,
  password_hash text,
  created_at timestamptz default now()
);

create table if not exists public.books (
  book_id bigint generated by default as identity primary key,
  title text not null,
  author text not null,
  publisher text,
  published_year integer,
  isbn text,
  category text,
  description text,
  cover_image_url text,
  difficulty_level text,
  created_at timestamptz default now()
);

create table if not exists public.topics (
  topic_id bigint generated by default as identity primary key,
  book_id bigint references public.books(book_id) on delete set null,
  topic_text text not null,
  topic_type text not null,
  difficulty_level integer,
  keywords text[],
  evaluation_criteria jsonb,
  created_at timestamptz default now()
);

create table if not exists public.assessments (
  assessment_id bigint generated by default as identity primary key,
  student_id bigint references public.users(user_id) on delete cascade,
  topic_id bigint references public.topics(topic_id) on delete set null,
  assessment_type text not null,
  status text not null,
  started_at timestamptz,
  submitted_at timestamptz,
  time_limit_minutes integer,
  word_count_min integer,
  word_count_max integer,
  created_at timestamptz default now()
);

create table if not exists public.answers (
  answer_id bigint generated by default as identity primary key,
  assessment_id bigint references public.assessments(assessment_id) on delete cascade,
  content text,
  word_count integer,
  char_count integer,
  paragraph_count integer,
  auto_saved_at timestamptz,
  submitted_at timestamptz,
  version integer default 1,
  created_at timestamptz default now()
);

create table if not exists public.evaluations (
  evaluation_id bigint generated by default as identity primary key,
  answer_id bigint references public.answers(answer_id) on delete cascade,
  assessment_id bigint references public.assessments(assessment_id) on delete cascade,
  student_id bigint references public.users(user_id) on delete set null,
  evaluator_type text,
  book_analysis_score integer,
  creative_thinking_score integer,
  problem_solving_score integer,
  language_expression_score integer,
  expression_score integer,
  total_score integer,
  grade text,
  percentile integer,
  spelling_errors integer,
  spacing_errors integer,
  grammar_errors integer,
  vocabulary_level numeric,
  overall_comment text,
  comprehensive_feedback text,
  detailed_feedback text,
  strengths text[],
  weaknesses text[],
  improvements text[],
  student_feedback jsonb,
  rubric jsonb,
  line_edits jsonb,
  teacher_note text,
  evaluated_at timestamptz,
  created_at timestamptz default now()
);

alter table public.evaluations
  add column if not exists student_feedback jsonb,
  add column if not exists rubric jsonb,
  add column if not exists line_edits jsonb,
  add column if not exists teacher_note text;

-- Open policies for development/testing (tighten before production)
alter table public.users enable row level security;
alter table public.books enable row level security;
alter table public.topics enable row level security;
alter table public.assessments enable row level security;
alter table public.answers enable row level security;
alter table public.evaluations enable row level security;

create policy "dev_read_users" on public.users for select using (true);
create policy "dev_write_users" on public.users for insert with check (true);
create policy "dev_update_users" on public.users for update using (true);
create policy "dev_delete_users" on public.users for delete using (true);

create policy "dev_read_books" on public.books for select using (true);
create policy "dev_write_books" on public.books for insert with check (true);
create policy "dev_update_books" on public.books for update using (true);
create policy "dev_delete_books" on public.books for delete using (true);

create policy "dev_read_topics" on public.topics for select using (true);
create policy "dev_write_topics" on public.topics for insert with check (true);
create policy "dev_update_topics" on public.topics for update using (true);
create policy "dev_delete_topics" on public.topics for delete using (true);

create policy "dev_read_assessments" on public.assessments for select using (true);
create policy "dev_write_assessments" on public.assessments for insert with check (true);
create policy "dev_update_assessments" on public.assessments for update using (true);
create policy "dev_delete_assessments" on public.assessments for delete using (true);

create policy "dev_read_answers" on public.answers for select using (true);
create policy "dev_write_answers" on public.answers for insert with check (true);
create policy "dev_update_answers" on public.answers for update using (true);
create policy "dev_delete_answers" on public.answers for delete using (true);

create policy "dev_read_evaluations" on public.evaluations for select using (true);
create policy "dev_write_evaluations" on public.evaluations for insert with check (true);
create policy "dev_update_evaluations" on public.evaluations for update using (true);
create policy "dev_delete_evaluations" on public.evaluations for delete using (true);

create table if not exists public.feedbacks (
  feedback_id bigint generated by default as identity primary key,
  evaluation_id bigint references public.evaluations(evaluation_id) on delete cascade,
  student_id bigint references public.users(user_id) on delete set null,
  assessment_id bigint references public.assessments(assessment_id) on delete set null,
  answer_id bigint references public.answers(answer_id) on delete set null,
  summary_intro text,
  summary_body text,
  summary_conclusion text,
  rubric jsonb,
  line_edits jsonb,
  strengths text[],
  weaknesses text[],
  improvements text[],
  teacher_note text,
  created_at timestamptz default now()
);

alter table public.feedbacks enable row level security;

create policy "dev_read_feedbacks" on public.feedbacks for select using (true);
create policy "dev_write_feedbacks" on public.feedbacks for insert with check (true);
create policy "dev_update_feedbacks" on public.feedbacks for update using (true);
create policy "dev_delete_feedbacks" on public.feedbacks for delete using (true);
