-- 사용자 테이블만 포함한 간단한 스키마
-- user_type: STUDENT, PARENT, SCHOOL_ADMIN, ASSESSMENT_TEACHER, QUESTION_DEVELOPER, SYSTEM_ADMIN
-- student_grade_level: GRADE_A, GRADE_B (2단계)

create table if not exists public.users (
  user_id bigint generated by default as identity primary key,
  email text not null unique,
  name text not null,
  user_type text not null,
  birth_date date,
  phone text,
  school_name text,
  school_id bigint,
  school_code text,
  grade integer,
  class_name text,
  student_code text,
  student_grade_level text,
  profile_image_url text,
  is_active boolean default true,
  password_hash text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create unique index if not exists users_student_code_unique
  on public.users(student_code)
  where student_code is not null;

-- 학교명 기반 영문 이니셜(3자리) 생성
create or replace function public.school_code_from_name(school_name text)
returns text
language plpgsql
immutable
as $$
declare
  cleaned text;
begin
  if school_name is null or length(trim(school_name)) = 0 then
    return 'SCH';
  end if;

  if school_name = '신명중학교' then
    return 'SMJ';
  end if;

  cleaned := regexp_replace(upper(school_name), '[^A-Z0-9]', '', 'g');
  if length(cleaned) >= 3 then
    return substr(cleaned, 1, 3);
  end if;

  return rpad(cleaned, 3, 'X');
end;
$$;

-- 학교 코드 + 6자리 랜덤으로 학생 고유 코드 생성
create or replace function public.generate_student_code(school_code text)
returns text
language plpgsql
as $$
declare
  prefix text;
  candidate text;
begin
  prefix := coalesce(nullif(school_code, ''), 'SCH');

  loop
    candidate := prefix || '_' ||
      lpad(((random() * 999999)::int)::text, 6, '0');
    exit when not exists (
      select 1 from public.users where student_code = candidate
    );
  end loop;

  return candidate;
end;
$$;

-- 사용자 저장 시 학교 코드/학생 코드 자동 부여
create or replace function public.users_assign_codes()
returns trigger
language plpgsql
as $$
begin
  if new.school_name is not null and (new.school_code is null or new.school_code = '') then
    new.school_code := public.school_code_from_name(new.school_name);
  end if;

  if new.user_type = 'STUDENT' and (new.student_code is null or new.student_code = '') then
    new.student_code := public.generate_student_code(new.school_code);
  end if;

  return new;
end;
$$;

drop trigger if exists trg_users_assign_codes on public.users;
create trigger trg_users_assign_codes
before insert or update of school_name, school_code, user_type, student_code
on public.users
for each row
execute function public.users_assign_codes();

-- RLS 설정
alter table public.users enable row level security;

-- 기존 정책 삭제
drop policy if exists "dev_read_users" on public.users;
drop policy if exists "dev_write_users" on public.users;
drop policy if exists "dev_update_users" on public.users;
drop policy if exists "dev_delete_users" on public.users;

-- 개발용 전체 접근 정책 (운영 전 수정 필요)
create policy "dev_read_users" on public.users for select using (true);
create policy "dev_write_users" on public.users for insert with check (true);
create policy "dev_update_users" on public.users for update using (true);
create policy "dev_delete_users" on public.users for delete using (true);

-- anon 역할 권한 (개발용)
grant usage on schema public to anon;
grant select on public.users to anon;
